### ISSUE TITLE
Familiarize with ROS

### ISSUE THREAD

**Issue by andrecabaco** [Te1moFernandes/PSA-P2-G3#2]

**Comment by andrecabaco** [comment]
Tutorial de instalação

https://www.youtube.com/watch?v=ZA7u2XPmnlo

**Comment by Te1moFernandes** [comment]
Instalado em todos, a especialização vem com a expêriencia :)

**Comment by Te1moFernandes** [comment]
Como vão os tutoriais de ROS? Alguns progressos? @andrecabaco @mafaldalemosmelo @ivodomingues

**Comment by andrecabaco** [comment]
Estão a ir.  Dos que aqui estão, há algum que aches mais importante?
http://wiki.ros.org/ROS/Tutorials

**Comment by Te1moFernandes** [comment]
Os primeiros 8 acho mesmo necessários. O 17 e 18 são interessantes nem que seja apenas ler para saberem como se processa o desenvolvimento do código de modo a não estar sempre a gastar os recurso necessários para o testar (isto é, utilização de gravações). Os tutoriais entre o 8 e o 17 não sei até que ponto serão necessários, se pesquisar um pouco sobre como funciona um publicador e subscritor :)

**Comment by Te1moFernandes** [comment]
Closed. All done.
