### ISSUE TITLE
Dar commit e push do trabalho feito até agora

### ISSUE THREAD

**Issue by Te1moFernandes** [Te1moFernandes/PSA-P2-G3#21]
https://angus.readthedocs.io/en/2016/LC-github.html#:~:text=git%20add%20script.txt%20will%20add%20the%20file%20script.txt,safe.%20git%20log%20will%20show%20you%20your%20history.

Dar commit e push do diretorio da carla e do rosbridge para o repositório.:
Arranjar forma de colocar os dois num mesmo repositório principal sem arranjar complicações.

**Comment by Te1moFernandes** [comment]
@miguelriemoliveira boa tarde professor, sabe quais são os códigos no terminal para dar upload (push) de uma certa pasta/diretório para o github?? 
O problema é que eu quero dar push da pasta da carla e do ros bridge para o nosso github mas como não estão no mesmo diretório não sei se é possivel... É possível? Se sim, como e quais são os códigos? 

Ps.: Se estivesse tudo no mesmo diretório era mais facil, é possível mover as pastas do rosbridge e do carla para uma só sem criar "erros" no launch dos programas?

**Comment by miguelriemoliveira** [comment]
Olá Telmo,

não é possível. Só o que está dentro da pasta repositório é que se pode adicionar ao github.

Quando a mover o rosbridge também não recomendo. Os colegas devem instalar o rosbridge como você fez.

**Comment by Te1moFernandes** [comment]
Ok, professor. Então mover a pasta da carla para o diretório que está o rosbridge vou supor que também não é aconselhado, certo?
Desde já obrigado.

**Comment by miguelriemoliveira** [comment]
Não, não é bom estar a mexer diretórios de um lado para o outro a não ser que saiba muito bem o que está a fazer, porque há várias variáveis da bash que podem conter estes caminho e se os muda elas deixam de ter os valores corretos.
