### ISSUE TITLE
CARLA

### ISSUE THREAD

**Issue by Te1moFernandes** [Te1moFernandes/PSA-P2-G3#6]
Pesquisar informação sobre CARLA

**Comment by andrecabaco** [comment]
Vídeo sobre os primeiros passos no CARLA
Link:
https://www.youtube.com/watch?v=EzxhkEQUJqY

**Comment by andrecabaco** [comment]
https://www.youtube.com/watch?v=Z7PLkcY9Mtk

**Comment by andrecabaco** [comment]
https://www.youtube.com/watch?v=AaJekfFR1KQ

**Comment by mafaldalemosmelo** [comment]
./CarlaUE4.sh -prefernvidia -quality-level=Low

**Comment by vhfmaia** [comment]
@Te1moFernandes  https://carla.readthedocs.io/en/latest/adv_rendering_options/

**Comment by Te1moFernandes** [comment]
Instalado e testado em todos os computadores do grupo

**Comment by Te1moFernandes** [comment]
https://carla.readthedocs.io/en/latest/adv_rendering_options/#off-screen-mode
